{extend name="base" /}
{block name="body"}
<div class="layui-card">
	<div class="layui-fluid">
	<div class="layui-row layui-col-space15">
	<div class="layui-col-md12">
	<div class="layui-card">
		<div class="layui-tab" lay-filter="test1">
		  <div class="layui-tab-content">
			<div class="layui-tab-item layui-show">
			  <div class="layui-card-body ">
				<form class="layui-form layui-col-space5" >
							  <div class="layui-inline layui-show-xs-block">
                                    <input type="text" name="uid" placeholder="SHOPID" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
								<input type="text" name="name" placeholder="用户名|手机号" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
                                <input class="layui-input"  autocomplete="off" placeholder="开始日期" value="{:date('Y-m-d 00:00:00')}" name="start" id="start">
								</div>
								<div class="layui-inline layui-show-xs-block">
									<input class="layui-input"  autocomplete="off" placeholder="截止日期" value="{:date('Y-m-d 23:59:59')}" name="end" id="end">
								</div>
                                <div class="layui-inline layui-show-xs-block">
                                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                                        <i class="layui-icon">&#xe615;</i></button>
									<button class="layui-btn layui-btn-danger" type="button" lay-submit="" lay-filter="all" lay-skin="select" lay-filter="type">
                                        全部</button>
                                </div>
								</form>
                        </div>
                        <div class="layui-card-body ">
                            <table class="layui-table" id="mlist" lay-filter="mlist">
                                <thead>
                                    <tr>
                                </thead>
                            </table>
                        </div>
			</div>
			
		  </div>
		</div>
                    </div>
                </div>
            </div>
        </div>
		</div>
{/block}
{block name="js"}
    <script>
	layui.use(['table','form','laydate','element'], function() {
        var table = layui.table,form = layui.form, $ = layui.jquery,laydate = layui.laydate,element = layui.element;;
        tableIn = table.render({
            elem: '#mlist',
            url: "",
            method: 'post',
			page:true,
			totalRow:true,
            data:[],
            cols: [[
			    {type: 'checkbox',width:30,minWidth:30},
                {field:'day',title:"日期", align: 'center', sort: true,width:180,totalRowText: '合计：'},
				{field:'name',title:"渠道", align: 'center', sort: true,width:180},
			    {field:'cid',title: '成功笔数',align: 'center',totalRow: true},
				{field:'money',title: '成功面额',align: 'center',totalRow: true},
				{field:'amount',title: '寄售结算',align: 'center',totalRow: true},
				{field:'xitmoney',title: '销售收入',align: 'center',totalRow: true},
                {field:'profit',title: '获利金额',align: 'center',totalRow: true},
				{field:'failed',title: '失败笔数',align: 'center',totalRow: true},
				{field:'failedmoney',title: '失败面额',align: 'center',totalRow: true}
            ]],
			limit:15,
			limits:[10,20,50,60],
			parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }, done: function () {
                fnSetNoDouble();//这里调用删除小数点
            }
        });

        function fnSetNoDouble() {
            setTimeout(function () {
                fnGetTotalDiv(3);
                fnGetTotalDiv(8);
                //删除数据所在列
            }, 10);
        }

        function fnGetTotalDiv(id) {
            var div = '.layui-table-total div:eq(' + id + ')';
            var a = $(div).html();
            if(a!= null)a =  a.replace(".00","");
            $(div).html(a);
        }

        element.on('tab(test1)', function(){
			$("#start").val('');
			$("#end").val('');
		  });
		form.on('submit(sreach)', function(obj){
            var st=$("#start").val(),se=$("#end").val();
            
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 tableIn.reload({
				     url: "{:url('/tongji/chanel')}",
					page:{curr:1},
                     where:{
						 STime:st,
						 ETime:se,
						 Uid:$("input[name=uid]").val(),
						 Name:$("input[name=name]").val()
                     }
                 });
				 layer.close(index);
        });
		form.on('submit(all)', function(obj){
            var st=$("#start").val(),se=$("#end").val();
			$("input[name=uid]").val('');
			$("input[name=name]").val('');
            
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 tableIn.reload({
				     url: "{:url('/tongji/chanel')}",
					 page:{curr:1},
                     where:{
                         STime:st,
                         ETime:se,
						 Uid:'',
						 Name:''
                     }
                 });
				 layer.close(index);
        });
		var nowTime=new Date();    
		var startTime=laydate.render({
			elem:'#start',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',//默认最大值为当前日期
			done:function(value,date){
				endTime.config.min={    	    		
					year:date.year,
					month:date.month-1,//关键
					date:date.date,
				};
                
				
			}
		})
			var endTime=laydate.render({
			elem:'#end',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				};

			}
		})
      });
	  
    </script>
{/block}