{extend name="base" /}
{block name="body"}
<style>
    .layui-word-a{
        margin-bottom: 1px;
    }

    .layui-word-a:before {
        width: 19px;
        content: "系";
        color: #FFF;
        display: inline-block;
        margin-right: 3px;
        padding: 2px;
        text-align: center;
        border-color: #198bfc;
        background-color: #198bfc;
        box-shadow: 1px 3px 13px rgba(25,139,252,.2);
        border-radius: 3px;
    }
    .layui-word:before {
        border-color: #01cf75;
        background-color: #01cf75;
        box-shadow: 1px 3px 13px rgba(1,207,117,.21);
        width: 19px;
        content: "商";
        color: #FFF;
        display: inline-block;
        margin-right: 3px;
        padding: 2px;
        text-align: center;
        border-radius: 3px;
    }
    .layui-table-cell {
        padding: 0 5px;
    }
</style>
<div class="layui-card">
    <div class="layui-card-body">
							  <form class="layui-form layui-col-space5" >
								<div class="layui-inline layui-show-xs-block">
                                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="starttime" value="{:date('Y-m-d 00:00:00',strtotime('-3 day'))}" id="starttime">
								</div>
								<div class="layui-inline layui-show-xs-block">
									<input class="layui-input"  autocomplete="off" placeholder="截止日期" name="endtime" value="{:date('Y-m-d H:i:s')}" id="endtime">
								</div>
								<div class="layui-inline layui-show-xs-block">
								 <select name="type" id="selt" lay-skin="select">
                                     <option value="number">充值账号</option>
									 <option value="shopid">SHOPID</option>
									 <option value="tmporder|orderno" {eq name="da.tc|default=''" value="1"}selected=""{/eq}>订单号</option>
									 <option value="money">充值金额</option>
								 </select>
                                </div>
								<div class="layui-inline layui-show-xs-block">
								<input type="hidden" id="typen" value="">
								<input type="hidden" id="money" value="">
                                    <input type="text" name="username" placeholder="搜索内容" autocomplete="off" value="{$da.str|default=''}" class="layui-input">
								</div>
							
								<input type="hidden" value="" name="state" id="seltt">
                                <div class="layui-inline layui-show-xs-block">
                                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                                        <i class="layui-icon">&#xe615;</i></button>
										</button>
										 

                                </div>
								<div class="layui-btn-group layui-show-xs-block" id="allbutton" style="display:block">
								   <button class="layui-btn" style="margin-bottom:8px" type="button" id="typeClick" lay-type="" >全 部</button>
								   {volist name="li" id="p"}
                                    <button class="layui-btn layui-btn-primary" style="margin-bottom:8px" type="button" id="typeClick" lay-type="{$p.geway}" >{$p.title}【{$p.mianzhi}】</button>
                                   {/volist}									
                                </div>
                                 <div class="layui-inline layui-show-xs-block" id="dorder">
                                        <button class="layui-btn layui-btn-default" type="button" id="sall" lay-type="0">全部订单</button>
								     	<button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="1">等待受理</button>
										<button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="2">正在处理</button>
								     	<button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="3">成功订单</button>
								     	<button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="4">失败订单</button>
                                        <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="5">待审核</button>
                                </div>
								</form>
								<input type="hidden" id="font-primary" >
                        </div>
		<table id="tableList" lay-filter="tableList"></table>
</div>
	<script type="text/html" id="number">
	   {{#  if(d.card_no.indexOf("/uploads/") != -1){ }}
	    <img src="{{d.card_no}}"  tb-img/>
	   {{#  } else { }}
	   <p id="share" lay-event="share">{{d.card_no}}</br>{{d.card_key}}</br>{{d.seccode}}</p>
	   {{# }}}
	</script>
	
<script type="text/html" id="idd">
    <div class="layui-form-item" style="margin-bottom:2px">
        <div class="layui-form-mid layui-word-a" style="padding:1px !important">{{d.orderno}}</div>
    </div>
    {{# if(d.tmporder!=null){}}
    <div class="layui-form-item" style="margin-bottom:2px">
        <div class="layui-form-mid layui-word" style="padding:1px !important">{{d.tmporder}}</div>
    </div>
    {{# }}}
</script>

<script type="text/html" id="caoz">
		<div class="layui-btn-group">
        {{# if(d.states==1){}}
    		<button class="layui-btn"  lay-event="chaxun" >查询</button>
    	{{# }else{ }}
    	    <button class="layui-btn layui-btn-disabled " href="" data-width="850px" data-height="500px" >查询</button>
		{{# }}}
		</div>
   </script>

{/block}
{block name="js"}
<script src="/static/simple/js/clipboard.min.js"></script>
<script>
    layui.use(['layer', 'form', 'table', 'laydate'], function () {
        var $ = layui.jquery,layer = layui.layer,form = layui.form,table = layui.table,laydate=layui.laydate;
        var stt=$("#starttime").val(),set=$("#endtime").val();
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/CashOrder/index')}?se="+set+"&st="+stt,
            where:{kk:'orderno',name:'{$da.str|default=''}'},
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {field:'id',type: 'checkbox',filter:"ids",width:30,minWidth:30},
				{toolbar: '#idd',title:"订单号", align: 'center', sort: true,width:200},
				{title:"商户信息", align: 'center',field:'uname', width:100},
			    {field:'title',title: '运营商',align: 'center',width:140,totalRowText: '合计：'},
				{title: '充值账号',field:'number',align: 'center',sort: true,width:160},
				{field:'money',title: '充值金额',style:"color:#c60",align: 'center',width:80},
				{field:'feilv',title: '费率',style:"color:#c60",align: 'center',width:80},
				{field:'price',title: '实际扣费',style:"color:#c60",align: 'center',width:100},
				{field:'amount',title: '使用充值卡',style:"color:#00a65a",align: 'center',totalRow: true,width:200},
				{field:'cashnum',title:'充值次数',style:"color:#e60040",align:'center',totalRow: true,width:80},
				{field:'atime', align: 'center',title:'提交时间',width:120},
				{field:'overtime', align: 'center',title:'耗时',width:120},
				{field:'state', title:'状态',align: 'center',width:100,sort: true},
                {field:'remarks', align: 'center',title:'备注',width:120},
                {field:'notifymsg', align: 'center',title:'回调信息',width:120},
                {toolbar: '#caoz', align: 'center',title:'操作',width:100}
                
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		var nowTime=new Date();    
		var startTime=laydate.render({
			elem:'#starttime',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',//默认最大值为当前日期
			done:function(value,date){
				endTime.config.min={    	    		
					year:date.year,
					month:date.month-1,//关键
					date:date.date,
					hours:date.hours,
					minutes:date.minutes,
					seconds:date.seconds
				};
				
			}
		})
		var endTime=laydate.render({
			elem:'#endtime',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				}
				
			}
		})

        table.on('tool(tableList)', function(obj) { //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
            var data = obj.data //获得当前行数据
                , layEvent = obj.event; //获得 lay-event 对应的值
            switch (layEvent) {
                case 'chaxun':
                    var indexs = layer.load(3, {
                        shade: [0.1,'#fff'] //0.1透明度的白色背景
                    });
                    $.post("{:url('/CashOrder/findOrder')}",{id:data.id},function (e) {
                        console.log(e);
                        layer.close(indexs);
                        layer.msg(e.msg, {
                            time: 1000,
                            shade: 0.3
                        },function(){
                            insTb.reload();
                        });
                    })
                    break;
            }
        })
		
		table.on('row(tableList)', function(obj){
		        var data = obj.data;
		        $("#font-primary").val("");
		    	var checkStatus = table.checkStatus("tableList"),str="";
                    $(checkStatus.data).each(function (i,o) {
                		str+=o.card_no+" "+o.card_key+"\n";
                    });
                    if($(this).find(".layui-form-checked").length==1){
    		            str+=data.card_no+" "+data.card_key+"\n";
    		        }else{
    		            str=str.replace(data.card_no+" "+data.card_key+"\n","");
    		        }
                $("#font-primary").val(str);
		})
		
		form.on('checkbox(layTableAllChoose)',function(data){
		        $("#font-primary").val("");
		        var data=table.cache.tableList;
		    	var checkStatus = table.checkStatus("tableList"),str="";
		    	if(checkStatus.data.length!=15){
                    $(data).each(function (i,o) {
                		str+=o.card_no+" "+o.card_key+"\n";
                    });
		    	}
                $("#font-primary").val(str);
		});
		
		 var clipboard1 = new ClipboardJS('#share', {
						text: function(trigger) {
						return $("#font-primary").val();
					  }
					});

        		clipboard1.on('success', function(e) {
        			console.log(e);
        			layer.msg((e.action=='copy'?'复制':'剪切')+'成功');
        		});
        		
        		clipboard1.on('error', function(e) {
        			layer.msg("内容为空");
        		});
	
		$("#printt").click(function(){
					var name=$("input[name=username]").val();
					var kk=$("#selt").val(),st=$("#starttime").val(),se=$("#endtime").val();
					var state=$("#seltt").val(),cl=$("#typen").val();
					location.href="{:url('/Order/export')}?name="+name+"&kk="+kk+"&st="+st+"&se="+se+"&state="+state+"&classa="+cl;
                    
		});

		
		  form.on('submit(sreach)', function(obj){
            loading =layer.load(1, {shade: [0.1,'#fff']});
            var name=$("input[name=username]").val();
			var kk=$("#selt").val(),st=$("#starttime").val(),se=$("#endtime").val();
			var state=$("#seltt").val(),cl=$("#typen").val();
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
						 kk:kk,
						 st:st,
						 se:se,
						 state:state,
						 classa:cl,
                     }
                 });
				 layer.close(index);
        });
		
		//卡类查询
		$("#allbutton").on("click","#typeClick",function(){
		    var e=$(this);
			e.siblings().addClass("layui-btn-primary");
			e.removeClass("layui-btn-primary");
			$("#typen").val(e.attr('lay-type'));
			loading =layer.load(1, {shade: [0.1,'#fff']});
            var name=$("input[name=username]").val();
			var kk=$("#selt").val(),st=$("#start").val(),se=$("#end").val();
			var state=$("#seltt").val(),cl=$("#typen").val();
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
						 kk:kk,
						 st:st,
						 se:se,
						 state:state,
						 classa:cl,
                     }
                 });
				 layer.close(index);
		});
		//状态查询
		$("#dorder").on("click","#sall",function(){
		    var e=$(this);
			e.siblings().addClass("layui-btn-primary");
			e.removeClass("layui-btn-primary");
			$("#seltt").val(e.attr('lay-type'));
            var name=$("input[name=username]").val();
			var kk=$("#selt").val(),st=$("#start").val(),se=$("#end").val();
			var state=$("#seltt").val(),cl=$("#typen").val();
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
						 kk:kk,
						 st:st,
						 se:se,
						 state:state,
						 title:cl,
                     }
                 });
		});
		$("#printno").click(function(){
				var st=$("#starttime").val(),se=$("#endtime").val();
				location.href="{:url('/CashOrder/export')}?st="+st+"&se="+se;
                    
		});

    });

</script>
{/block}
