{extend name="base" /}
{block name="body"}
<div class="layui-card">
	<div class="layui-fluid">
	<div class="layui-row layui-col-space15">
	<div class="layui-col-md12">
	<div class="layui-card">
		<div class="layui-tab" lay-filter="test1">
		  <div class="layui-tab-content">
			<div class="layui-tab-item layui-show">
			  <div class="layui-card-body ">
				<form class="layui-form layui-col-space5" >
                    <div class=""layui-group>
						<div class="layui-inline layui-show-xs-block">
                                    <input type="text" name="uid" placeholder="SHOPID" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
								<input type="text" name="name" placeholder="用户名|手机号" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
                                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="start" value="" id="start">
								</div>
								<div class="layui-inline layui-show-xs-block">
									<input class="layui-input"  autocomplete="off" placeholder="截止日期" name="end"  id="end">
								</div>
                                        <div class="layui-inline layui-show-xs-block">
                                            <select name="class" lay-filter="modelshop" id="classa" >
                                                <option value="0">全部运营商</option>
                                                {volist name="classlist" id="p"}
                                                <option value="{$p.ids}" >{$p.cardtitle}</option>
                                                {/volist}
                                            </select>
                                        </div>
                                        <div class="layui-inline layui-show-xs-block">
                                            <select name="money" lay-filter="modelshopa" id="money" >
                                                <option value="0">全部面值</option>
                                                {volist name="mianzhi" id="p"}
                                                <option value="{$p.mianzhi}" >{$p.mianzhi}</option>
                                                {/volist}
                                            </select>
                                    </div>
                                <div class="layui-inline layui-show-xs-block">
                                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                                        <i class="layui-icon">&#xe615;</i></button>

                        </div>
                    </div>
                    <div class=""layui-group>
                            <div class="layui-input-inline">
                                <input type="checkbox" name="ontime" title="按提交日期" checked><div class="layui-unselect layui-form-checkbox"><span>按提交日期</span><i class="layui-icon layui-icon-ok"></i></div>
                                <input type="checkbox" name="onclass" title="按运营商" ><div class="layui-unselect layui-form-checkbox "><span>按运营商</span><i class="layui-icon layui-icon-ok"></i></div>
                                <input type="checkbox" name="oncard" title="按寄售卡商"><div class="layui-unselect layui-form-checkbox"><span>按寄售卡商</span><i class="layui-icon layui-icon-ok"></i></div>
                                <input type="checkbox" name="onrechang" title="按充值商户"><div class="layui-unselect layui-form-checkbox"><span>按充值商户</span><i class="layui-icon layui-icon-ok"></i></div>
                                <input type="checkbox" name="onmoney" title="按面值"><div class="layui-unselect layui-form-checkbox"><span>按面值</span><i class="layui-icon layui-icon-ok"></i></div>
                            </div>

                    </div>
                  </form>
                        </div>
                        <div class="layui-card-body ">
                            <table class="layui-table" id="mlist" lay-filter="mlist">
                                <thead>
                                </thead>
                            </table>
                        </div>
			</div>
		  </div>
		</div>
                    </div>
                </div>
            </div>
        </div>
		</div>
{/block}
{block name="js"}
    <script>
	layui.use(['table','form','laydate','element'], function() {
        var table = layui.table,form = layui.form, $ = layui.jquery,laydate = layui.laydate,element = layui.element;
        tableIn = table.render({
            elem: '#mlist',
            id:"idTest",
            url: "",
            method: 'post',
            page:true,
            totalRow:true,
            cols: [],
            data:[],
            limit:15,
            limits:[10,20,50,60],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                    "code": res.code, //解析接口状态
                    "msg": res.msg, //解析提示文本
                    "count": res.data.total, //解析数据长度
                    "data": res.data.data //解析数据列表
                };
            }
        });
		element.on('tab(test1)', function(){
			$("#start").val('');
			$("#end").val('');
		  });
		form.on('submit(sreach)', function(obj){
		    if(obj.field.ontime==undefined && obj.field.onclass==undefined && obj.field.oncard==undefined && obj.field.onrechang==undefined && obj.field.onmoney==undefined){
                layer.msg("至少选择一个展示条件");
                return;
            }
		    var cols=[
                {field:'amoney',title: '面值总额',align: 'center',sort: true,totalRow: true},
                {field:'bigmoney',title: '大卡总额',align: 'center',sort: true,totalRow: true},
                {field:'smallmoney',title: '小卡总额',align: 'center',sort: true,totalRow: true},
                {field:'amount',title: '销售额',align: 'center',sort: true,totalRow: true},
                {field:'settl',title: '成本金额',align: 'center',sort: true,totalRow: true},
                {field:'ids',title: '笔数',align: 'center',sort: true,totalRow: true},
                {field:'dai',title: '代充费用',align: 'center',sort: true,totalRow: true},
            ];
		    var ontime="",onclass="",onc="",onr="",classa="",onmoney='';
            let oncard={field:'username',title:"寄售商户",sort: true, align: 'center', width:120};
            if(obj.field.ontime==undefined && obj.field.onclass==undefined  && obj.field.onrechang==undefined){
                oncard={field:'username',title:"寄售商户",sort: true, align: 'center', width:120,totalRowText: '合计：'};
            }
            if(obj.field.oncard=="on"){
                cols.splice(0,0,oncard);
                onc='on';
            }

            let onrechang={field:'company',title:"充值商户", align: 'center',sort: true, width:120};
            if(obj.field.ontime==undefined && obj.field.onclass==undefined && obj.field.oncard==undefined ){
                onrechang={field:'company',title:"充值商户", align: 'center',sort: true, width:120,totalRowText: '合计：'};
            }
            if(obj.field.onrechang=="on"){
                if(obj.field.oncard=="on"){
                    cols.splice(1,0,onrechang);
                }else{
                    cols.splice(0,0,onrechang);
                }
                onr='on';
            }

            let classs={field:'title',title:"运营商", align: 'center',sort: true, width:130};
            if(obj.field.ontime==undefined)classs={field:'title',title:"运营商", align: 'center',sort: true, width:130,totalRowText: '合计：'};
            if(obj.field.onclass=="on" ){
                if(obj.field.oncard=="on" && obj.field.onrechang=="on"){
                    cols.splice(2,0,classs);
                }else{
                    cols.splice(1,0,classs);
                }
                onclass="on";
            }

            let money={field:'money',title:"面值", align: 'center',sort: true, width:100};
            if(obj.field.onmoney=='on'){
                cols.splice(-7,0,money);
                onmoney="on";
            }

            let ti={field:'day',title:"日期", align: 'center', width:160,sort: true,totalRowText: '合计：'};
            if(obj.field.ontime=="on"){
                cols.unshift(ti);
                ontime='on';
            }
            classa=$("#classa").val();
            var st=$("#start").val(),se=$("#end").val();
           
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
            table.render({
                     elem: '#mlist',
				     url: "{:url('/Carduse/index')}",
                    page:true,
                    totalRow:true,
                    toolbar: true ,//开启头部工具栏，并为其绑定左侧模板
                    defaultToolbar: ['filter',  'exports'],
                     cols: [cols],
                     where:{
						 STime:st,
						 ETime:se,
						 ontime:ontime,
                         onclass:onclass,
                         onmoney:onmoney,
                         oncard:onc,
                         onrechang:onr,
                         classa:classa,
                         name:$("input[name=name]").val(),
                         uid:$("input[name=uid]").val(),
                         money:$("#money").val()
                     },limit:15,
                      limits:[10,20,50,60],
                    parseData: function(res){ //res 即为原始返回的数据
                        return {
                            "code": res.code, //解析接口状态
                            "msg": res.msg, //解析提示文本
                            "count": res.data.total, //解析数据长度
                            "data": res.data.data //解析数据列表
                        };
                    },
                      done: function (res, curr, count) {
                        table.resize('idTest');
                     }
                 });
            layer.close(index);
        });

		var nowTime=new Date();    
		var startTime=laydate.render({
			elem:'#start',
			type:'datetime',
            value:"{:date('Y-m-d 00:00:00',strtotime('-1 month'))}",
			btns: ['confirm'],
			max:'23:59:59',//默认最大值为当前日期
			done:function(value,date){
				endTime.config.min={    	    		
					year:date.year,
					month:date.month-1,//关键
					date:date.date,
					hours:date.hours,
					minutes:date.minutes,
					seconds:date.seconds
				};
                
				
			}
		})
			var endTime=laydate.render({
			elem:'#end',
			type:'datetime',
			btns: ['confirm'],
            value:"{:date('Y-m-d 23:59:59')}",
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				};
			}
		})

      });
	  
    </script>
{/block}