{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <div class="layui-btn-group">
           <a ew-href="{:url('/user/email')}" class="layui-btn layui-btn-warm" ><i class="layui-icon layui-icon-release"></i>发送邮件</a>
        </div>
        
    </div>
        <table id="tableList" lay-filter="tableList"></table>

</div>


<script type="text/html" id="tableTBTrack">
        <div class="layui-btn-group">
		<button type="button" class="layui-btn" lay-event="bianji">编辑</button>
		</div>
</script>
{/block}
{block name="js"}
<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/Email/index')}",
            where:{id:$("input[name=field]").val()},
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            toolbar: true //开启头部工具栏，并为其绑定左侧模板
            ,defaultToolbar: ['filter'],
            cols: [[
                {field: 'id',align: 'center', sort: true, title: 'ID',width:60},
                {field:'yonghu', align: 'center', title: '接收用户',width:320},
				{field:'sendnum', align: 'center', title: '本次发送数量',minWidth:100},
				{field:'jindu', align: 'center',  title: '发送进度',width:120},
				{field: 'sendok', align: 'center', title: '发送成功',width:120},
				{field: 'title', align: 'center', title: '发送标题',width:180},
				{field: 'content', align: 'center', title: '发送内容',width:400},
				{field: 'err', align: 'center', title: '失败记录',width:300},
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		
		 table.on('tool(tableList)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
			var data = obj.data //获得当前行数据
			,layEvent = obj.event; //获得 lay-event 对应的值
			switch(layEvent){
				case "bianji":
				  var one=openUrl("编辑会员",'600px','410px',"{:Url('/user/edit')}?id="+data.id);
				break;
			}
			function openUrl(title,width,height,url){
				var index = layer.open({
						title: title,
						type: 2,
						shadeClose:true,
						area: [width, height],
						content: url,
					})
				return index;
			}
		 })

		  form.on('submit(sreach)', function(obj){
            var name=$("input[name=username]").val();
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 shop_id:name
                     }
                 });
        });
        form.on('submit(print)', function(obj){
            var name=$("input[name=username]").val();
            window.location.href="{:url('/user/export')}"+"?type="+$("#seltt").val();
        });

        $("#alluser").on("click","#sall",function(){
            var e=$(this);
            e.siblings().addClass("layui-btn-primary");
            e.removeClass("layui-btn-primary");
            $("#seltt").val(e.attr('lay-type'));
            var state=$("#seltt").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    state:state
                }
            });
        });
        
        
    });

</script>
{/block}
