{extend name="base" /}
{block name="body"}
<style>
    .layui-table-cell {
        padding: 0 5px;
</style>
<div class="layui-card">
    <div class="layui-card-body">
		<form class="layui-form layui-col-space5" >
            <div class="layui-inline layui-show-xs-block">
                <button class="layui-btn layui-btn-danger ajax-batch" type="button" href="{:url('/CashOrdererr/del')}" data-tips="确定批量删除数据吗?" data-tab="tableList" ><i class="layui-icon"></i>批量删除</button>
            </div>
					<div class="layui-inline layui-show-xs-block">
                                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="starttime" id="starttime">
					</div>
								<div class="layui-inline layui-show-xs-block">
									<input class="layui-input"  autocomplete="off" placeholder="截止日期" name="endtime" id="endtime">
								</div>
								<div class="layui-inline layui-show-xs-block">
								 <select name="type" id="selt" lay-skin="select">
									 <option value="shopid">SHOPID</option>
									 <option value="tmporder">订单号</option>
									 <option value="money">充值金额</option>
									 <option value="number">充值账号</option>
								 </select>
                                </div>
								<div class="layui-inline layui-show-xs-block">
								<input type="hidden" id="typen" value="">
								<input type="hidden" id="money" value="">
                                    <input type="text" name="username" placeholder="搜索内容" autocomplete="off" value="{$da.str|default=''}" class="layui-input">
								</div>
							
								<input type="hidden" value="" name="state" id="seltt">
                                <div class="layui-inline layui-show-xs-block">
                                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                                        <i class="layui-icon">&#xe615;</i></button>
										</button>
                                </div>
								<div class="layui-btn-group layui-show-xs-block" id="allbutton" style="display:block">
								   <button class="layui-btn" style="margin-bottom:8px" type="button" id="typeClick" lay-type="" >全 部</button>
								   {volist name="li" id="p"}
                                    <button class="layui-btn layui-btn-primary" style="margin-bottom:8px" type="button" id="typeClick" lay-type="{$p.geway}" >{$p.title}【{$p.mianzhi}】</button>
                                   {/volist}									
                                </div>
								</form>
								<input type="hidden" id="font-primary" >
                        </div>
		<table id="tableList" lay-filter="tableList"></table>
</div>

{/block}
{block name="js"}
<script src="/static/simple/js/clipboard.min.js"></script>
<script>
    layui.use(['layer', 'form', 'table', 'laydate'], function () {
        var $ = layui.jquery,layer = layui.layer,form = layui.form,table = layui.table,laydate=layui.laydate;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/CashOrdererr/index')}",
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {field:'id',type: 'checkbox',filter:"ids",width:30,minWidth:30},
				{field:'tmporder',title:"订单号", align: 'center', sort: true,width:200},
				{title:"商户信息", align: 'center',field:'uname', width:100},
			    {field:'title',title: '运营商',align: 'center',width:140,totalRowText: '合计：'},
				{title: '充值账号',field:'number',align: 'center',sort: true,width:160},
				{field:'money',title: '充值金额',style:"color:#c60",align: 'center',width:80},
				{field:'feilv',title: '费率',style:"color:#c60",align: 'center',width:80},
				{field:'price',title: '金额校验',style:"color:#c60",align: 'center',width:100},
				{field:'atime', align: 'center',title:'提交时间',width:120},
				{field:'state', title:'返回状态',align: 'center',width:100,sort: true},
                {field:'remarks', align: 'center',title:'备注'},
                {field:'notifymsg', align: 'center',title:'回掉'},
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		var nowTime=new Date();    
		var startTime=laydate.render({
			elem:'#starttime',
			type:'datetime',
			btns: ['confirm'],
			max:'nowTime',//默认最大值为当前日期
			done:function(value,date){
				endTime.config.min={    	    		
					year:date.year,
					month:date.month-1,//关键
					date:date.date,
					hours:date.hours,
					minutes:date.minutes,
					seconds:date.seconds
				};
				
			}
		})
		var endTime=laydate.render({
			elem:'#endtime',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				}
				
			}
		})
		
		table.on('row(tableList)', function(obj){
		        var data = obj.data;
		        $("#font-primary").val("");
		    	var checkStatus = table.checkStatus("tableList"),str="";
                    $(checkStatus.data).each(function (i,o) {
                		str+=o.card_no+" "+o.card_key+"\n";
                    });
                    if($(this).find(".layui-form-checked").length==1){
    		            str+=data.card_no+" "+data.card_key+"\n";
    		        }else{
    		            str=str.replace(data.card_no+" "+data.card_key+"\n","");
    		        }
                $("#font-primary").val(str);
		})
		
		form.on('checkbox(layTableAllChoose)',function(data){
		        $("#font-primary").val("");
		        var data=table.cache.tableList;
		    	var checkStatus = table.checkStatus("tableList"),str="";
		    	if(checkStatus.data.length!=15){
                    $(data).each(function (i,o) {
                		str+=o.card_no+" "+o.card_key+"\n";
                    });
		    	}
                $("#font-primary").val(str);
		});

		
		  form.on('submit(sreach)', function(obj){
            loading =layer.load(1, {shade: [0.1,'#fff']});
            var name=$("input[name=username]").val();
			var kk=$("#selt").val(),st=$("#starttime").val(),se=$("#endtime").val();
			var state=$("#seltt").val(),cl=$("#typen").val();
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
						 kk:kk,
						 st:st,
						 se:se,
						 state:state,
						 classa:cl,
                     }
                 });
				 layer.close(index);
        });
		
		//卡类查询
		$("#allbutton").on("click","#typeClick",function(){
		    var e=$(this);
			e.siblings().addClass("layui-btn-primary");
			e.removeClass("layui-btn-primary");
			$("#typen").val(e.attr('lay-type'));
			loading =layer.load(1, {shade: [0.1,'#fff']});
            var name=$("input[name=username]").val();
			var kk=$("#selt").val(),st=$("#start").val(),se=$("#end").val();
			var state=$("#seltt").val(),cl=$("#typen").val();
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
						 kk:kk,
						 st:st,
						 se:se,
						 state:state,
						 classa:cl,
                     }
                 });
				 layer.close(index);
		});


    });

</script>
{/block}
