{extend name="base" /}
{block name="body"}
<div class="layui-card">
	<div class="layui-fluid">
	<div class="layui-row layui-col-space15">
	<div class="layui-col-md12">
	<div class="layui-card">
		<div class="layui-tab" lay-filter="test1">
		  <div class="layui-tab-content">
			<div class="layui-tab-item layui-show">
			  <div class="layui-card-body ">
				<form class="layui-form layui-col-space5" >
							  <div class="layui-inline layui-show-xs-block">
                                    <input type="text" name="uid" placeholder="SHOPID" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
								<input type="text" name="name" placeholder="用户名|手机号" autocomplete="off" class="layui-input">
								</div>
								<div class="layui-inline layui-show-xs-block">
                                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="start" value="{:date('Y-m-d 00:00:00')}" id="start">
								</div>
								<div class="layui-inline layui-show-xs-block">
									<input class="layui-input"  autocomplete="off" placeholder="截止日期" name="end" value="{:date('Y-m-d 23:59:59')}" id="end">
								</div>
                                <div class="layui-inline layui-show-xs-block">
                                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                                        <i class="layui-icon">&#xe615;</i></button>
									<button class="layui-btn layui-btn-danger" type="button" lay-submit="" lay-filter="all" lay-skin="select" lay-filter="type">
                                        全部</button>
                                    <button class="layui-btn" type="button" id="printt" lay-event="LAYTABLE_EXPORT">
                                        <i class="layui-icon layui-icon-export">  </i></button>
                                </div>

                  </form>
                        </div>
                        <div class="layui-card-body ">
                            <table class="layui-table" id="mlist" lay-filter="mlist">
                                <thead>
                                </thead>
                            </table>
                        </div>
			</div>
		  </div>
		</div>
                    </div>
                </div>
            </div>
        </div>
		</div>
{/block}
{block name="js"}
    <script>
	layui.use(['table','form','laydate','element'], function() {
        var table = layui.table,form = layui.form, $ = layui.jquery,laydate = layui.laydate,element = layui.element;
        var st=$("#start").val(),se=$("#end").val();
        tableIn = table.render({
            elem: '#mlist',
            url: "{:url('/Shopdaily/index')}?STime="+st+"&ETime="+se,
            method: 'post',
			page:true,
			totalRow:true,
            cols: [[
			   {type: 'checkbox',width:30,minWidth:30},
                {field:'uptime',title:"日期", align: 'center', width:200},
				{field:'username',title:"用户名|手机号", align: 'center', width:180,totalRowText: '合计：'},
			    {field:'shopid',title: '商户ID',align: 'center'},
				{field:'money',title: '余额',align: 'center'},
                {field:'price',title: '成功提现',align: 'center',totalRow: true},
                {field:'loadmoney',title: '提现处理中',align: 'center'},
                {field:'data',title: '提现渠道',align: 'center'},

            ]],
			limit:15,
			limits:[10,20,50,60],
			parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });


		element.on('tab(test1)', function(){
			$("#start").val('');
			$("#end").val('');
		  });
		form.on('submit(sreach)', function(obj){
            var st=$("#start").val(),se=$("#end").val();
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 tableIn.reload({
				     url: "{:url('/Shopdaily/index')}",
					page:{curr:1},
                     where:{
						 STime:st,
						 ETime:se,
						 Uid:$("input[name=uid]").val(),
						 Name:$("input[name=name]").val()
                     }
                 });
				 layer.close(index);
        });
		form.on('submit(all)', function(obj){
            var st=$("#start").val(),se=$("#end").val();
			$("input[name=uid]").val('');
			$("input[name=name]").val('');
           
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 tableIn.reload({
				     url: "{:url('/Shopdaily/index')}",
					 page:{curr:1},
                     where:{
                         STime:st,
                         ETime:se,
						 Uid:'',
						 Name:''
                     }
                 });
				 layer.close(index);
        });
		var nowTime=new Date();    
		var startTime=laydate.render({
			elem:'#start',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',//默认最大值为当前日期
			done:function(value,date){
				endTime.config.min={    	    		
					year:date.year,
					month:date.month-1,//关键
					date:date.date,
					hours:date.hours,
					minutes:date.minutes,
					seconds:date.seconds
				};
               
				
			}
		})
			var endTime=laydate.render({
			elem:'#end',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				};
                startTime.config.min={
                    year:date.year,
                    month:date.month-1,//关键
                    date:date.date-7,
                }
				
			}
		})

        $("#printt").click(function(){
            var name=$("input[name=name]").val();
            var st=$("#start").val(),se=$("#end").val();
            var uid=$("input[name=uid]").val();
           
            location.href="{:url('/Shopdaily/export')}?type=0&Name="+name+"&STime="+st+"&ETime="+se+"&Uid="+uid;
        });
      });
	  
    </script>
{/block}