{extend name="base" /}
{block name="body"}
<style>
    .layui-form-switch{
        margin-top:0;
    }
    .lay-span{
        display: block;
        padding: 5px 5px;
        background: #FF5722;
        text-align: center;
        color: #fff;
        border-radius: 3px;
    }
    .layui-card .layui-card-body .layui-btn-group{
        margin-bottom:0;
    }
    .layui-card .layui-card-body .layui-table td{
        max-width:450px
    }
</style>
<style>
    .layui-word-a{
        margin-bottom: 1px;
    }

    .layui-word-a:before {
        width: 19px;
        content: "急";
        color: #FFF;
        display: inline-block;
        margin-right: 3px;
        padding: 2px;
        text-align: center;
        border-color: #ff422b;
        background-color: #ff5722;
        box-shadow: 1px 3px 13px #ffb39c;
        border-radius: 3px;
    }

    .layui-input-block{
        margin-left: 0px;
        min-height: 0px;
    }

</style>
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form layui-col-space5" >
            <div class="layui-inline layui-show-xs-block">

                <button class="layui-btn layui-btn-normal ajax-batch" type="button" data-tips="确定批量重发订单吗?" data-tab="tableList" href="{:url('/Order/batchOrder',['type'=>'rest'])}">批量重试</button>
                <button class="layui-btn layui-btn-danger ajax-batch" type="button" data-tips="确定批量成功订单吗?" data-tab="tableList" href="{:url('/Order/batchOrder',['type'=>'success'])}">批量成功</button>
                <button class="layui-btn layui-btn-normal ajax-batch" type="button" data-tips="确定批量失败订单吗?" data-tab="tableList" href="{:url('/Order/batchOrder',['type'=>'err'])}">批量失败</button>
                <button class="layui-btn layui-btn-primary ajax-batch" type="button" data-tips="确定批量查询订单吗?" data-tab="tableList" href="{:url('/Order/batchOrder',['type'=>'chaxun'])}">批量查询</button>
                <button class="layui-btn layui-btn-danger ajax-batch" type="button" data-tips="确定取消订单吗?" data-tab="tableList" href="{:url('/Userorder/cancel')}">批量取消</button>
            </div>
            <div class="layui-group">
                <div class="layui-inline layui-show-xs-block">
                    <input type="checkbox" name="timestype" checked lay-skin="switch" lay-filter="timetype" lay-text="提交时间|处理时间"><div class="layui-btn layui-unselect layui-form-switch" lay-skin="_switch"><em>on</em><i></i></div>
                </div>
                <div class="layui-inline layui-show-xs-block">
                    <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="starttime" value="{:date('Y-m-d 00:00:00', strtotime('-7 days'))}" id="starttime">
                </div>
                <div class="layui-inline layui-show-xs-block">
                    <input class="layui-input"  autocomplete="off" placeholder="截止日期" name="endtime" value="{:date('Y-m-d H:i:s')}" id="endtime">
                </div>
                <div class="layui-inline layui-show-xs-block">
                    <select name="type" id="selt" lay-skin="select">
                        <option value="card_no">卡号</option>
                        <option value="shopid">SHOPID</option>
                        <option value="batchno|orderno" {eq name="da.tc|default=''" value="1"}selected=""{/eq}>订单号</option>
                        <option value="money">提交面值</option>
                        <option value="settle_amt">成功面值</option>
                        <option value="card_key">卡密</option>
                    </select>
                </div>
                <div class="layui-inline layui-show-xs-block">
                    <input type="hidden" id="typen" value="">
                    <input type="hidden" id="money" value="">
                    <input type="hidden" id="timetype" value="on">
                    <input type="text" name="username" placeholder="搜索内容" value="{$da.str|default=''}" autocomplete="off" class="layui-input">
                </div>
                <input type="hidden" value="" name="state" id="seltt">
                <div class="layui-inline layui-show-xs-block">
                    <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" >
                        <i class="layui-icon">&#xe615;</i></button>
                    <button class="layui-btn" type="button" id="printt" lay-event="LAYTABLE_EXPORT">
                        <i class="layui-icon layui-icon-export">  </i></button>

                    <button class="layui-btn layui-btn-danger" lay-submit=""  lay-filter="share" id="share" type="button">批量复制</button>
                </div>
            </div>

            <div class="layui-btn-group layui-show-xs-block" id="allbutton">
                <button class="layui-btn" style="margin-bottom:8px" type="button" id="typeClick" lay-type="" >全 部</button>
                {volist name="li" id="p"}
                <button class="layui-btn layui-btn-primary" style="margin-bottom:8px" type="button" id="typeClick" lay-type="{$p.type}" >{$p.title}</button>
                {/volist}
            </div>
            <div class="layui-group">
                <div class="layui-inline layui-show-xs-block" id="dorder">
                    <button class="layui-btn layui-btn-default" type="button" id="sall" lay-type="0">全部订单</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="1">等待受理</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="2">正在处理</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="3">成功订单</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="4">失败订单</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="5">待审核</button>
                    <button class="layui-btn layui-btn-primary" type="button" id="sall" lay-type="6">可赔付</button>
                </div>
            </div>

            <input type="hidden" id="font-primary" >
        </form>
    </div>
    <table id="tableList" lay-filter="tableList"></table>

</div>
<script type="text/html" id="number">
    {{#  if(d.card_no.indexOf("/uploads/") != -1){ }}
    <img src="{{d.card_no}}"  tb-img/>
    {{#  } else { }}
    <p id="share" lay-event="share">{{d.card_no}}</br>{{d.card_key}}</br>{{d.seccode}}</p>
    {{# }}}
</script>
<script type="text/html" id="caoz">
    <div class="layui-btn-group">
        {{# if(d.type!=0 || d.ispei>0){}}
        {{# if(d.getstate==8){}}
        {{# if(d.ispei==1){}}
        <button class="layui-btn ajax-iframe" href="{:url('/Order/peifu')}?id={{d.id}}" data-width="850px" data-height="500px" >订单赔付</button>
        {{#  } else { }}
        <button class="layui-btn layui-btn-danger">已赔付</button>
        {{# }}}
        {{#  } else { }}
        <button class="layui-btn layui-btn-disabled">订单赔付</button>
        {{# }}}
        {{# if(d.type!=0){}}
        <button class="layui-btn layui-btn-normal"  lay-event="chaxun" >查询</button>
        {{#  } else { }}
        <button class="layui-btn layui-btn-disabled">查询</button>
        {{# }}}
        {{#  } else { }}
        <button class="layui-btn layui-btn-disabled">订单赔付</button>
        <button class="layui-btn layui-btn-disabled">查询</button>
        {{# }}}

    </div>
</script>
<script type="text/html" id="idd">

    <div class="layui-form-item" style="margin-bottom:2px">
        <div class="layui-form-mid " style="padding:1px !important">{{d.orderno}}</div>
    </div>
    <button class="layui-btn layui-btn-normal ajax-tips" style="height:26px;line-height:26px" data-tips="确定执行成功操作?"  href="{:url('/Order/setStatus')}?id={{d.id}}&type=success">成功</button>
    <button class="layui-btn ajax-tips" data-tips="确定执行失败操作?" style="height:26px;line-height:26px"  href="{:url('/Order/setStatus')}?id={{d.id}}&type=error">失败</button>
</script>
<script type="text/html" id="xit">
    {{d.xit}}
</script>
<script type="text/html" id="state">
    {{#  if(d.isrest== 1){ }}
    <span class="text-danger">暂停</span>
    {{#  } else { }}
    {{d.state}}
    {{# }}}

</script>
<script type="text/html" id="but">
    <p>{{d.username}}</p>
</script>
<script type="text/html" id="amount">
    金：{{d.amount}}</p>
    <span class="text-danger">率：{{d.feilv}}</span>
</script>
<script type="text/html" id="priority">
    {{#  if(d.type == 0 && d.getstate<2){ }}
    <input type="text" name="priority" value="{{d.priority}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/Order/editpriority')}?order={{d.orderno}}">
    {{#  } else { }}
    --
    {{# }}}
</script>
{/block}
{block name="js"}
<script src="/static/simple/js/clipboard.min.js"></script>
<script>
    layui.use(['layer', 'form', 'table', 'laydate'], function () {
        var $ = layui.jquery,layer = layui.layer,form = layui.form,table = layui.table,laydate=layui.laydate;
        var stt=$("#starttime").val(),set=$("#endtime").val();
        var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/Order/index')}?se="+set+"&st="+stt,
            page: true,
            where:{kk:'{$da.field|default=''}',name:'{$da.str|default=''}'},
            limit:15,
            limits:[15,30,45,60,75,90,1000],
            cellMinWidth: 100,
            toolbar: true //开启头部工具栏，并为其绑定左侧模板
            ,defaultToolbar: ['filter'],
            cols: [[
                {field:'id',type: 'checkbox',filter:"ids",width:30,minWidth:30},
                {toolbar: '#idd',title:"订单号",field:"order", align: 'center', sort: true,width:190},
                {toolbar: '#but',title:"商户信息",field:"shopid", align: 'center', width:120},
                {field:'title',title: '运营商',align: 'center',width:115,totalRowText: '合计：'},
                {title: '卡号/卡密',toolbar:'#number',field:"number",align: 'left',sort: true,width:180},
                {field:'money',title: '提交面值',style:"color:#c60",align: 'center',width:100},
                {field:'amount',toolbar:'#amount',title: '寄售结算-付',style:"color:#00a65a",align: 'left',totalRow: true,width:120},
                {field:'xitmoney',title:'销卡结算-收',style:"color:#e60040",align:'center',totalRow: true,width:120},
                {field:'priority', align: 'center',toolbar:"#priority",title:'优先级',width:100},
                {field:'atime', align: 'center',title:'提交时间',width:120},
                {field:'chutime', align: 'center',title:'处理时间',width:120},
                {field:'state',toolbar: '#state', title:'状态',align: 'center',width:100,sort: true},
                {field:'oper', align: 'center',title:'销卡渠道',width:100},
                {field:'remarks', align: 'center',title:'备注',width:140},
                {align:'center',title:'操作',toolbar: '#caoz',width:260}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                    "code": res.code, //解析接口状态
                    "msg": res.msg, //解析提示文本
                    "count": res.data.total, //解析数据长度
                    "data": res.data.data //解析数据列表
                };
            }
        });
        var nowTime=new Date();
        var startTime=laydate.render({
            elem:'#starttime',
            type:'datetime',
            btns: ['confirm'],
            max:'23:59:59',
            done:function(value,date){
                endTime.config.min={
                    year:date.year,
                    month:date.month-1,//关键
                    date:date.date,
                    hours:date.hours,
                    minutes:date.minutes,
                    seconds:date.seconds
                };
               
            }

        })
        var endTime=laydate.render({
            elem:'#endtime',
            type:'datetime',
            btns: ['confirm'],
            max:'23:59:59',
            done:function(value,date){
                startTime.config.max={
                    year:date.year,
                    month:date.month-1,//关键
                    date:date.date,
                };

            }
        })



        table.on('tool(tableList)', function(obj) { //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
            var data = obj.data //获得当前行数据
                , layEvent = obj.event; //获得 lay-event 对应的值

            switch (layEvent) {
                case 'chaxun':
                    var indexs = layer.load(3, {
                        shade: [0.1,'#fff'] //0.1透明度的白色背景
                    });
                    $.post("{:url('/Order/findorder')}",{id:data.id},function (e) {
                        console.log(e);
                        layer.close(indexs);
                        var str="无返回信息";
                        if(e.msg!="" && e.msg!=null)str=e.msg;
                        console.log(str);
                        layer.msg(str, {
                            time: 1000,
                            shade: 0.3
                        },function(){
                            insTb.reload();
                        });
                    })
                    break;
              

            }
        })
        table.on('row(tableList)', function(obj){
            var data = obj.data;
            $("#font-primary").val("");
            var checkStatus = table.checkStatus("tableList"),str="";
            $(checkStatus.data).each(function (i,o) {
                str+=o.card_no+" "+o.card_key+"\n";
            });
            if($(this).find(".layui-form-checked").length==1){
                str+=data.card_no+" "+data.card_key+"\n";
            }else{
                str=str.replace(data.card_no+" "+data.card_key+"\n","");
            }
            $("#font-primary").val(str);
        })

        form.on('checkbox(layTableAllChoose)',function(data){
            $("#font-primary").val("");
            var data=table.cache.tableList;
            var checkStatus = table.checkStatus("tableList"),str="";
            if(checkStatus.data.length!=15){
                $(data).each(function (i,o) {
                    str+=o.card_no+" "+o.card_key+"\n";
                });
            }
            $("#font-primary").val(str);
        });

        var clipboard1 = new ClipboardJS('#share', {
            text: function(trigger) {
                var str=$("#font-primary").val();
                if(str=="" || str==null){
                    layer.msg("请选择要复制的数据");
                    return false;
                }
                return str;
            }
        });

        clipboard1.on('success', function(e) {
            console.log(e);
            layer.msg((e.action=='copy'?'复制':'剪切')+'成功');
        });

        clipboard1.on('error', function(e) {
            console.log(e);
            layer.msg("内容为空");
        });

        $("#printt").click(function(){
            var name=$("input[name=username]").val();
            var kk=$("#selt").val(),st=$("#starttime").val(),se=$("#endtime").val();

            var state=$("#seltt").val(),cl=$("#typen").val();
            
            location.href="{:url('/Order/export')}?name="+name+"&kk="+kk+"&st="+st+"&se="+se+"&state="+state+"&classa="+cl;

        });

        form.on('switch(timetype)', function(data){
            if(data.elem.checked==true){
                $("#timetype").val('on');
            }else{
                $("#timetype").val('off');
            }
        })
        form.on('submit(sreach)', function(obj) {
            var name = $("input[name=username]").val();
            var kk = $("#selt").val(), st = $("#starttime").val(), se = $("#endtime").val();

           
           
            var state=$("#seltt").val(),cl=$("#typen").val(),timetype=$("#timetype").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    name:name,
                    kk:kk,
                    st:st,
                    se:se,
                    state:state,
                    classa:cl,
                    timetype:timetype
                }
            });
        });

        //卡类查询
        $("#allbutton").on("click","#typeClick",function(){
            var e=$(this);
            e.siblings().addClass("layui-btn-primary");
            e.removeClass("layui-btn-primary");
            $("#typen").val(e.attr('lay-type'));
            var name=$("input[name=username]").val();
            var kk=$("#selt").val(),st=$("#start").val(),se=$("#end").val();
            var state=$("#seltt").val(),cl=$("#typen").val(),timetype=$("#timetype").val();
           
            insTb.reload({
                page:{curr:1
                },
                where:{
                    name:name,
                    kk:kk,
                    st:st,
                    se:se,
                    state:state,
                    classa:cl,
                    timetype:timetype
                }
            });
        });
        //状态查询
        $("#dorder").on("click","#sall",function(){
            var e=$(this);
            e.siblings().addClass("layui-btn-primary");
            e.removeClass("layui-btn-primary");
            $("#seltt").val(e.attr('lay-type'));

            var name=$("input[name=username]").val();
            var kk=$("#selt").val(),st=$("#start").val(),se=$("#end").val();
            var state=$("#seltt").val(),cl=$("#typen").val(),timetype=$("#timetype").val();
           
            insTb.reload({
                page:{curr:1
                },
                where:{
                    name:name,
                    kk:kk,
                    st:st,
                    se:se,
                    state:state,
                    classa:cl,
                    timetype:timetype
                }
            });
        });

        // 点击图片放大
        $(document).off('click.tbImg').on('click.tbImg', '[tb-img]', function () {
            layer.photos({photos: {data: [{src: $(this).attr('src')}]}, shade: .1, closeBtn: true});
        });
    });

</script>
{/block}
