{extend name="base" /}
{block name="body"}
<style>
.layui-form-switch{
	margin-top:0;
}
.lay-span{
	display: block;
    padding: 5px 5px;
    background: #FF5722;
    text-align: center;
    color: #fff;
    border-radius: 3px;
}
.layui-card .layui-card-body .layui-btn-group{
	margin-bottom:0;
}
.layui-card .layui-card-body .layui-table td{
	max-width:450px
}
</style>
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form layui-col-space5" >
            <div class="layui-group">
                <div class="layui-inline layui-show-xs-block">
                    <input type="text" name="username" placeholder="银行名称" autocomplete="off" class="layui-input">
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">选择地区</label>
                    <div class="layui-input-inline">
                        <select name="province" id="province" lay-filter="province">
                            <option value="">请选择省</option>
                            {foreach name="citys" id="p"}
                              <option value="{$p.code}">{$p.region}</option>
                            {/foreach}
                        </select>
                    </div>
                    <div class="layui-input-inline">
                        <select name="citys" id="citys" lay-filter="citys">
                            <option value="">请选择市</option>
                        </select>
                    </div>

                </div>
                <button class="layui-btn" lay-submit="" type="button" lay-filter="sreach" lay-skin="select"><i class="layui-icon"></i></button>
                <div class="layui-btn-group">
                    <a href="{:url('/Prcptcd/adddata')}" class="layui-btn ajax-iframe" data-width="600px" data-height="440px"><i class="fa fa-plus-circle"></i> 添加行号</a>
                </div>
            </div>
        </form>
            <div class="layui-btn-group layui-show-xs-block" id="allbutton" style="margin-top: 20px">
                <button class="layui-btn {notempty name="$da['type']"}layui-btn-primary{/notempty}" style="margin-bottom:8px" type="button" id="typeClick" lay-type="" >全 部</button>
                {volist name="info" id="p"}
                 <button class="layui-btn {neq name="$da['type']|default='0'" value="$p.procode"}layui-btn-primary{/neq}" style="margin-bottom:8px" type="button" id="typeClick" lay-type="{$p.procode}" >{$p.bankName}</button>
                {/volist}
            </div>
		<table id="tableList" lay-filter="tableList"></table>
    </div>
</div>
 <script type="text/html" id="abbr">
        <input type="text" name="abbr" value="{{d.abbr}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/Bank/edit')}?id={{d.id}}">
</script>
	
<script type="text/html" id="status">
     <input type="checkbox" name="state" lay-skin="switch" lay-filter="*" lay-text="正常|禁用" data-url="{:url('/Bank/edit')}?id={{d.id}}" {{d.state==1?'checked':''}}>
</script>
<script type="text/html" id="tableTBTrack">
   <div class="layui-btn-group">
       <button type="button" class="layui-btn layui-btn-success" lay-event="bianji">编辑</button>
       <button type="button" class="layui-btn layui-btn-danger" lay-event="del">删除</button>
  </div>
</script>
{/block}
{block name="js"}
<script>
    var type="{$da['type']|default=''}";
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/Prcptcd/index')}",
            where:{type: type},
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {field: 'bankName',align: 'content', title: '总行名称',width:200},
                {title:'银行编号', align: 'content', field: 'bank_code',width:120},
                {field:'diqu', align: 'content', title: '所属地区'},
                {title:'银行名称', align: 'content', field: 'bankname'},
                {title:'银联行号', align: 'content', field: 'prcptcd',width:180},
                {align: 'center', toolbar: '#tableTBTrack', title: '操作'}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		 table.on('tool(tableList)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
			var data = obj.data //获得当前行数据
			,layEvent = obj.event; //获得 lay-event 对应的值
			switch(layEvent){
				case "bianji":
				  var one=openUrl("编辑银行卡",'600px','440px',"{:Url('/Prcptcd/adddata')}?id="+data.id);
				break;
				case "del":
				  layer.confirm('确定删除？', {
						icon: 3,
						title: '提示'
					}, function (index) {
						var index = layer.msg('删除中，请稍候', {
							icon: 16,
							time: false,
							shade: 0.3
						});
						$.ajax({
							url: "{:Url('/Prcptcd/del')}?id="+data.id,
							type: 'post',
							dataType: 'json',
							success: function (result) {
								if (result.code === 1) {
									insTb.reload();
								}
								layer.close(index);
								layer.msg(result.msg);
							},
							error: function (xhr, state, errorThrown) {
								layer.close(index);
								layer.msg(state + '：' + errorThrown);
							}
						});
					});
				break;
			}
			function openUrl(title,width,height,url){
				var index = layer.open({
						title: title,
						type: 2,
						shadeClose:true,
						area: [width, height],
						content: url,
					})
				return index;
			}
		  });
		  form.on('submit(sreach)', function(obj){
            var name=$("input[name=username]").val();
			var index = layer.msg('查询中，请稍候', {
							icon: 16,
							time: false,
							shade: 0.3
						});
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 name:name,
                         type:$("#typen").val(),
                         citys:$("#citys").val()
                     }
                 });
				 layer.close(index);
        });

        //卡类查询
        $("#allbutton").on("click","#typeClick",function(){
            var e=$(this);
            e.siblings().addClass("layui-btn-primary");
            e.removeClass("layui-btn-primary");
            $("#typen").val(e.attr('lay-type'));
            var name=$("input[name=username]").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    name:name,
                    type:e.attr('lay-type'),
                    citys:$("#citys").val()
                }
            });
        });

        form.on('select(province)', function(data){ //no是那个lay-filter的值
            var nos=$("#province").val();//获得选中的option的值
            $.post("{:url('/Prcptcd/citys')}",{code:nos},function(e){
                var str="";
                for(var x in e.data){
                    str += '<option value = "' + e.data[x].code + '">' + e.data[x].region + '</option>'
                }
                $("#citys").html(str);
                form.render();//最后记得渲染
            })

        });

    });

</script>
{/block}
