{extend name="base" /}
{block name="body"}
<style>
.layui-body-header.show {
    display: block;
}
.layui-form-switch{
	margin-top:0;
}
.lay-span{
	display: block;
    padding: 5px 5px;
    background: #FF5722;
    text-align: center;
    color: #fff;
    border-radius: 3px;
}
.layui-card .layui-card-body .layui-btn-group{
	margin-bottom:0;
}
.layui-card .layui-card-body .layui-table td{
	max-width:450px
}
    .money{
        display: inline-block;
    }
    .money .xian{
        display: block;
    }
</style>

<div class="layui-card">
    <div class="layui-card-body">
         <form class="layui-form layui-col-space5">
	    <div class="layui-inline layui-show-xs-block">
			<input type="text" name="keys" placeholder="查询内容" autocomplete="off" class="layui-input">
		</div>
		<div class="layui-inline layui-show-xs-block">
                <select name="type" id="selt" lay-skin="select">
                    <option value="name">真实姓名</option>
                    <option value="shopid">SHOPID</option>
                    <option value="username">用户名</option>
                    <option value="mobile">手机号</option>
                    
                </select>
            </div>
		<button class="layui-btn" lay-submit="" type="button" lay-filter="sreach" lay-skin="select"><i class="layui-icon"></i></button>
		
        <div class="layui-btn-group">
            <a href="{:url('/user/add',['shop_id' => input('shop_id')])}" class="layui-btn ajax-iframe" data-width="600px" data-height="400px"><i class="fa fa-plus-circle"></i> 添加会员</a>
            <a lay-submit="" lay-filter="print" class="layui-btn layui-btn-primary"><i class="fa fa-file-excel-o"></i> 导出会员</a>
			<a href="javascript:void(0)" class="layui-btn layui-btn-danger">寄售余额：{$money}</a>
        </div>
        <input type="hidden" value="" name="state" id="seltt">
        <div class="layui-btn-group" id="alluser">
            <button type="button" class="layui-btn "  id="sall" lay-type="0">全部</button>
            <button type="button" class="layui-btn layui-btn-primary" id="sall" lay-type="1">寄售商户</button>
            <button type="button" class="layui-btn layui-btn-primary" id="sall" lay-type="2">充值商户</button>
            <button type="button" class="layui-btn layui-btn-primary" id="sall" lay-type="3">注销用户</button>
        </div>
        <a ew-href="{:url('/user/email')}" class="layui-btn layui-btn-warm" ><i class="layui-icon layui-icon-release"></i>发送邮件</a>
        </form>
    </div>
        <table id="tableList" lay-filter="tableList"></table>

</div>
<script type="text/html" id="username">
    {{#  if(d.username == "" | d.username==null){ }}--{{#  } else { }}{{d.username}}{{#  } }}
</script>
<script type="text/html" id="apilib">
     <input type="checkbox" name="apilib" lay-skin="switch" lay-filter="*" lay-text="开启|关闭" data-url="{:url('/user/edit')}?type={{d.atype}}&id={{d.id}}" {{d.apilib==1?'checked':''}}>
</script>
<script type="text/html" id="user">
    {{#  if(d.atype == 0){ }}
    <span  style="color:red">【{{d.type}}】</span>
    {{#  } else { }}
    <span  style="color:green">【{{d.type}}】</span>
    {{#  } }} 
    {{d.shopid}}
     {{#  if(d.atype ==1 && d.auth==1){ }}
    <p><button class="layui-btn layui-btn-normal " lay-event="jiakuan"  style="height:20px;line-height:20px" >加减款</button></p>
    {{#  } }} 

</script>

<script type="text/html" id="qqopenid">
    {{#  if(d.qqopenid == "" | d.qqopenid==null){ }}
    <span class="lay-span" style="background:#c2c2c2">未绑定</span>
	{{#  } else { }}
	<span class="lay-span" >已绑定</span>
	{{#  } }}
</script>
<script type="text/html" id="wxopenid">
    {{#  if(d.wxopenid == "" | d.wxopenid==null){ }}
    <span class="lay-span" style="background:#c2c2c2">未绑定</span>
	{{#  } else { }}
	<span class="lay-span" >已绑定</span>
	{{#  } }}
</script>

<script type="text/html" id="yuer">
    {{#  if(d.atype ==1 ){ }}
    <span class="money">
        <span class="xian" id="usermoney{{d.id}}">余:{{d.money}}</span>
        <span class="xian" id="userxin{{d.id}}" style="color:red">信:{{d.xin}}</span>
        <span><button class="layui-btn layui-btn-danger " lay-event="getmoney"  style="height:20px;line-height:20px" >刷新余额</button></span>
    </span>

	{{#  } else { }}
	{{d.money}}
	{{#  } }}
</script>

<script type="text/html" id="status">
     <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="正常|禁用" data-url="{:url('/user/edit')}?id={{d.id}}" {{d.status==1?'checked':''}}>
</script>

<script type="text/html" id="cashapi">
    <input type="checkbox" name="cashapi" lay-skin="switch" lay-filter="*" lay-text="开启|关闭" data-url="{:url('/user/edit')}?type={{d.type}}&id={{d.id}}" {{d.cashapi==1?'checked':''}}>
</script>

<script type="text/html" id="yuti">
    {{#  if(d.atype !=1 ){ }}
    <input type="text" name="yuti" value="{{d.yuti}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/user/edityuti')}?id={{d.id}}">
    {{#  } else { }}
    --
    {{#  } }}
</script>

<script type="text/html" id="iscash">
    <input type="checkbox" name="iscash" lay-skin="switch" lay-filter="*" lay-text="正常结算|不可结算" data-url="{:url('/user/edit')}?id={{d.id}}" {{d.iscash==1?'checked':''}}>
</script>
<script type="text/html" id="tableTBTrack">
   <div class="layui-btn-group">
        <button type="button" class="layui-btn" style="background: #ff2e14;"  lay-event="ren">查看认证信息</button>
		<button type="button" class="layui-btn" lay-event="bianji">编辑</button>
       {{# if(d.atype==0){}}
		<button type="button" class="layui-btn layui-btn-warm" lay-event="feilv">费率</button>
       {{# }else{ }}
        <button type="button" class="layui-btn layui-btn-warm" lay-event="shop">费率</button>
       {{# } }}
		<button type="button" class="layui-btn " lay-event="loginlog">登陆记录</button>
		<button type="button" class="layui-btn" style="background: #1e9fff;" lay-event="txlog">提现方式</button>
		<button type="button" class="layui-btn layui-btn-normal" lay-event="moneylog">资金记录</button>
		{{# if(d.utype!=3){}}
		 <button type="button" class="layui-btn layui-btn-danger" lay-event="del">注销</button>
		 {{# } }}
		</div>
</script>
{/block}
{block name="js"}

<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/User/index')}",
            where:{id:$("input[name=field]").val()},
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            toolbar: true //开启头部工具栏，并为其绑定左侧模板
            ,defaultToolbar: ['filter'],
            cols: [[
                {type:'numbers',title:'#'},
                {field: 'shopid',align: 'center',toolbar:'#user', sort: true, title: '商户ID',width:140},
                {field:'rategroup', align: 'center', title: '费率组'},
                {field:'username',templet:'#username', align: 'center', title: '用户名',minWidth:120},
                {field:'company', align: 'center', title: '主体名称',minWidth:120},
				{field:'qq', align: 'center', title: '用户QQ',minWidth:120},
				{field:'retype', align: 'center', title: '认证类型'},
				{field: 'mobile', align: 'center', title: '手机号',width:120},
				{field: 'money', align: 'left', toolbar:'#yuer',title: '余额',width:130},
				//{field: 'price', align: 'left', title: '总余额',width:120},
				{field: 'assets', align: 'center', title: '下级',width:80},
				{field: 'last_login_ip', align: 'center', title: '登录IP',width:140},
				{align: 'center',  title: '注册时间',field:'create_time',width:160},
                {field:'apilib',align: 'center',  title: 'API开关',templet:'#apilib'},
                {field:'cashapi',align: 'center',  title: '预提比例(%)',templet:'#yuti',width:110},
                {field:'iscash',align: 'center',  title: '面值不符',templet:'#iscash',minWidth: 120},
				{field:"qqopenid",align: 'center',  title: 'QQ互联',templet:'#qqopenid'},
				{field:'wxopenid',align: 'center',  title: '微信绑定',templet:'#wxopenid'},
				{field:'status',align: 'center',  title: '状态',templet:'#status'},
                {field:'caoz',align: 'center', toolbar: '#tableTBTrack', title: '操作',width: 630}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		
		 table.on('tool(tableList)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
			var data = obj.data //获得当前行数据
			,layEvent = obj.event; //获得 lay-event 对应的值
			switch(layEvent){
				case "bianji":
				  var one=openUrl("编辑会员",'600px','410px',"{:Url('/user/edit')}?id="+data.id);
				break;
				case "getmoney":
				    $.post("{:Url('/user/upmoney')}",{id:data.id},function(e){
				        if(e.code==1){
				            $("#usermoney"+data.id).text("余:"+e.data.money);
                            $("#userxin"+data.id).text("信:"+e.data.xin);
                            layer.msg("刷新成功");
                        }else{
                            layer.msg("刷新失败，可以重试");
                        }
                    })
				    break;
				case "jiakuan":
				  var one=openUrl("会员【"+data.shopid+"】加减款",'600px','560px',"{:Url('/user/editMoney')}?id="+data.id);
				break;
				case "feilv":
				  var one=openUrl("编辑寄售费率【"+data.shopid+"】<span style='color:red'>(点击费率出现输入框,修改完成点击其他地方自动保存)</span>",'880px','680px',"{:Url('/user/feilv')}?id="+data.id);
				break;
				case "loginlog":
				  var one=openUrl("登陆记录【"+data.shopid+"】",'980px','680px',"{:Url('/user/log')}?id="+data.id);
				break;
				case "txlog":
				  var one=openUrl("提现方式【"+data.shopid+"】",'1080px','680px',"{:Url('/user/txlog')}?id="+data.id);
				break;
				case "moneylog":
				   var one=openUrl("资金记录【"+data.shopid+"】",'980px','680px',"{:Url('/user/moneylog')}?id="+data.id);
				break;
				case "ren":
				    var one=openUrl("【"+data.shopid+"】认证信息",'920px','680px',"{:url('/user/authreal')}?id="+data.id);
				break;
				case 'shop':
				    var one=openUrl("编辑充值费率【"+data.shopid+"】<span style='color:red'>(点击费率出现输入框,修改完成点击其他地方自动保存)</span>",'880px','680px',"{:Url('/user/usershopfeilv')}?id="+data.id);
				    break;
				case "del":
				    $.post("{:url('/User/getUser')}",{id:data.id},function(e){
				        if(e.code==1){
				            var html="<div class='clearfix layer-text'>";
    				        html+="<blockquote class='layui-elem-quote' style='border-left-color: #f60;font-size:14px;color:#f60'><p>注销后不能恢复</p>";
    				        html+="<p>需要完成所有订单、提现后进行注销。</p></blockquote></div><form class='layui-form'>";
    				        html+='<div class="layui-form-item"><label class="layui-form-label">账户余额</label>';
    				        html+='<div class="layui-form-mid layui-word-aux text-danger">'+data.money+'</div></div>';
    				        html+='<div class="layui-form-item"><label class="layui-form-label">未完寄售</label>';
    				        html+='<div class="layui-form-mid layui-word-aux text-danger">'+e.data.order+' 笔</div></div>';
    				        html+='<div class="layui-form-item"><label class="layui-form-label">未完充值</label>';
    				        html+='<div class="layui-form-mid layui-word-aux text-danger">'+e.data.cash+' 笔</div></div>';
    				        html+='<div class="layui-form-item">';
    				        html+='</div></form>';
    				        var df=layer.open({
                              type: 1,
                              shade: false,
                              area: ['380px', 'auto'],
                              title: '注销账户：'+data.shopid, //不显示标题
                              content: html,
                              btn: ['确认注销','取消注销'],
                              btn1: function(index, layero) {
                                 if(e.data.money>10){
                                     layer.msg("余额大于10，请先清空余额");
                                     return false;
                                 }
                                 if(e.data.order>0){
                                     layer.msg("有未完成寄售订单，请先完成");
                                     return false;
                                 }
                                 if(e.data.cash>0){
                                     layer.msg("有未完成充值订单，请先完成");
                                     return false;
                                 }
                                  if(e.data.money<0){
                                     layer.msg("有授信金额未清零，不能注销");
                                     return false;
                                 }
                                 deluser(e.data.uid);
                                 layer.close(index);
                              },
                              btn2: function(index, layero){
                                    layer.close(index);
                                   return false;
                                }
                            });
				        }else{
				            layer.msg(e.msg);
				        }
				    })
				    
				    
				break;
			}
			function openUrl(title,width,height,url){
				var index = layer.open({
						title: title,
						type: 2,
						shadeClose:true,
						area: [width, height],
						content: url,
					})
				return index;
			}

			function deluser(id) {
						var index = layer.msg('注销中，请稍候', {
							icon: 16,
							time: false,
							shade: 0.3
						});
						$.ajax({
							url: "{:Url('/user/del')}?id="+id,
							type: 'post',
							dataType: 'json',
							success: function (result) {
								if (result.code === 1) {
									insTb.reload();
								}
								layer.close(index);
								layer.msg(result.msg);
							},
							error: function (xhr, state, errorThrown) {
								layer.close(index);
								layer.msg(state + '：' + errorThrown);
							}
						});
					}
		  });
		  form.on('submit(sreach)', function(obj){
		      var kk=$("#selt").val();
              var name=$("input[name=keys]").val();
               var state=$("#seltt").val();
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
                          state:state,
						 keys:name,
						 type:kk
                     }
                 });
        });
        form.on('submit(print)', function(obj){
            var name=$("input[name=username]").val();
            window.location.href="{:url('/user/export')}"+"?type="+$("#seltt").val();
        });

        $("#alluser").on("click","#sall",function(){
            var e=$(this);
            e.siblings().addClass("layui-btn-primary");
            e.removeClass("layui-btn-primary");
            var kk=$("#selt").val();
            var name=$("input[name=keys]").val();
            $("#seltt").val(e.attr('lay-type'));
            var state=$("#seltt").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    state:state,
					 keys:name,
					 type:kk
                }
            });
        });
        
        
    });

</script>

{/block}
