{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form layui-col-space5" >
            <div class="layui-inline layui-show-xs-block">
                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="starttime" id="starttime">
            </div>
            <div class="layui-inline layui-show-xs-block">
                <input class="layui-input"  autocomplete="off" placeholder="截止日期" name="endtime" id="endtime">
            </div>
            <div class="layui-inline layui-show-xs-block">
                <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                    <i class="layui-icon">&#xe615;</i></button>
            </div>
        </form>
    </div>
    <table id="tableList" lay-filter="tableList"></table>
</div>
{/block}
{block name="js"}
<script src="/static/simple/js/clipboard.min.js"></script>
<script>
    layui.use(['layer', 'form', 'table', 'laydate'], function () {
        var $ = layui.jquery,layer = layui.layer,form = layui.form,table = layui.table,laydate=layui.laydate;
        var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/user/log',['id'=>$id])}",
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cols: [[
                {field:'shopid',title:"商户ID", align: 'center',width:100},
                {field:'pc',title:"客户端", align: 'center', width:100},
                {field:'shop_name',title: '会员账号',align: 'center',width:120},
                {title: 'IP地址',field:'ip',style:"color:#ff5722",align: 'left',width:120},
                {field:'area',title: '地区',style:"color:#c60",align: 'left',width:100},
                {field:'remark', align: 'left',title:'备注',width:100},
                {field:'type', align: 'left',title:'操作行为'},
                {field:'create_time', align: 'left',title:'操作时间',width:180},
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                    "code": res.code, //解析接口状态
                    "msg": res.msg, //解析提示文本
                    "count": res.data.total, //解析数据长度
                    "data": res.data.data //解析数据列表
                };
            }
        });

        var nowTime=new Date();
        var startTime=laydate.render({
            elem:'#starttime',
            type:'datetime',
            btns: ['confirm'],
            max:'nowTime',//默认最大值为当前日期
            done:function(value,date){
                endTime.config.min={
                    year:date.year,
                    month:date.month-1,//关键
                    date:date.date,
                    hours:date.hours,
                    minutes:date.minutes,
                    seconds:date.seconds
                };

            }
        })
        	var endTime=laydate.render({
			elem:'#endtime',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				}
				
			}
		})

        form.on('submit(sreach)', function(obj){
            var st=$("#starttime").val(),se=$("#endtime").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    st:st,
                    se:se
                }
            });
            layer.close(index);
        });


    });

</script>
{/block}
