{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form layui-col-space5" >
            <div class="layui-inline layui-show-xs-block">
                <input class="layui-input"  autocomplete="off" placeholder="开始日期" name="starttime" id="starttime">
            </div>
            <div class="layui-inline layui-show-xs-block">
                <input class="layui-input"  autocomplete="off" placeholder="截止日期" name="endtime" id="endtime">
            </div>
             <div class="layui-inline layui-show-xs-block">
			<input type="text" name="keys" id="keys" placeholder="查询内容" autocomplete="off" class="layui-input">
    		</div>
    		<div class="layui-inline layui-show-xs-block">
                    <select name="class" id="selt" lay-skin="select">
                        <option value="orderno">订单号</option>
                    </select>
                </div>
            <div class="layui-inline layui-show-xs-block">
                <button class="layui-btn" type="button" lay-submit="" lay-filter="sreach" lay-skin="select" lay-filter="type">
                    <i class="layui-icon">&#xe615;</i></button>
                    <button class="layui-btn layui-btn-danger" type="button" lay-submit="cha" lay-filter="cha" >
                    加款记录</button>
            </div>
        </form>
    </div>
    <table id="tableList" lay-filter="tableList"></table>
</div>
{/block}
{block name="js"}
<script src="/static/simple/js/clipboard.min.js"></script>
<script>
    layui.use(['layer', 'form', 'table', 'laydate'], function () {
        var $ = layui.jquery,layer = layui.layer,form = layui.form,table = layui.table,laydate=layui.laydate;
        var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/user/moneylog',['id'=>$id])}",
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cols: [[
                {field:'addtime',title:"操作时间", align: 'center',width:180},
                {field:'type',title:"操作类型", align: 'center', width:100},
                {field:'price',title: '变动金额',align: 'center',width:150},
                {title: '变动后余额',field:'money',style:"color:#ff5722",align: 'left',width:150},
                {field:'orderno',title: '关联订单',style:"color:#c60",align: 'left',width:200},
                {field:'data', align: 'left',title:'备注',width:200},
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                    "code": res.code, //解析接口状态
                    "msg": res.msg, //解析提示文本
                    "count": res.data.total, //解析数据长度
                    "data": res.data.data //解析数据列表
                };
            }
        });
        var nowTime=new Date();
        var startTime=laydate.render({
            elem:'#starttime',
            type:'datetime',
            btns: ['confirm'],
            max:'23:59:59',
            done:function(value,date){
                endTime.config.min={
                    year:date.year,
                    month:date.month-1,//关键
                    date:date.date,
                    hours:date.hours,
                    minutes:date.minutes,
                    seconds:date.seconds
                };

            }
        })
       	var endTime=laydate.render({
			elem:'#endtime',
			type:'datetime',
			btns: ['confirm'],
			max:'23:59:59',
			done:function(value,date){   	   
				startTime.config.max={
						year:date.year,
						month:date.month-1,//关键
						date:date.date,
				}
				
			}
		})

        form.on('submit(sreach)', function(obj){
            var st=$("#starttime").val(),se=$("#endtime").val();
            var classtype=$("#selt").val(),keys=$("#keys").val();
            insTb.reload({
                page:{curr:1
                },
                where:{
                    st:st,
                    se:se,
                    classtype:classtype,
                    keys:keys,
                    type:''
                }
            });
        });
        
        	//卡类查询
		form.on("submit(cha)",function(){
		    var classtype=$("#selt").val(),keys=$("#keys").val();
		    var e=$(this);
                 insTb.reload({
					page:{curr:1
						 },
                     where:{
						 type:5,
						 classtype:classtype,
                         keys:keys
                     }
                 });
		});

    });

</script>
{/block}
