{extend name="base" /}
{block name="body"}
       <div class="layui-fluid">
            <div class="layui-row">
                <form class="layui-form">
                      <div class="layui-form">
							  <table class="layui-table">
								<colgroup>
								   <col width="110">
								  <col width="170">
								  <col width="110">
								  <col width="180">
								  <col width="130">
								  <col >
								 <col >
								</colgroup>
								<tbody>
								  <tr>
									<td>订单号</td>
									<td>{$res.orderno}</td>
									<td>运营商</td>
									<td colspan=3>{$res.classa}</td>
								  </tr>
								  <tr>
									<td>卡号</td>
									<td>{$res.card_no}</td>
									<td>密码</td>
									<td>{$res.card_key|default='--'}</td>
									<td>验证码/CVV2码</td>
									<td>{$res.seccode|default='--'}</td>
								  </tr>
								  <tr>
									<td>提交面额</td>
									<td>{$res.money}</td>
                                      <td>卡状态</td>
                                      <td>{$res.state|raw}</td>
								  </tr>


								  <tr>
									<td>提交时间</td>
									<td>{$res.create_time}</td>
									<td>处理时间</td>
									<td colspan=3>{$res.update_time} </td>
								  </tr>
								  <tr>
									<td>提交IP</td>
									<td>{$res.ip}</td>
									<td>渠道</td>
									<td colspan=3>{$res.atype} </td>
								  </tr>
								  
								  <tr>
                                   <td>卡可用</td>
                                      <td colspan=2>
                                       <div class="layui-inline">
                                           <div class="layui-input-inline">
                                               <input type="hidden" id="textid" value="{$res.id}"><input id="RealMoney" type="text" value="{$res.money}" class="layui-input" placeholder="成功面额" style="width:150px;float: left;" />
                                           </div>
                                           <div class="layui-input-inline">
                                               <button class="layui-btn" lay-filter="sok" lay-submit="">卡可用</button>
                                           </div>
                                       </div>
								  </td>
                                <td class="am-text-left">
                                    标记失败
                                </td>
                                <td colspan=2>

								<div class="layui-inline">
                                    <div class="layui-input-inline">
                                        <input id="txtErrinfo" name="txtErrinfo" style="width:150px;    float: left;"  type="text" class="layui-input" placeholder="失败信息" />
                                    </div>
								  <div class="layui-input-inline">
									<button class="layui-btn " lay-filter="sno" lay-submit="">失败</button>
								  </div>
								</div>                                    
                                </td>
                                
                            </tr>
								</tbody>
							  </table>
							</div>
                </form>
            </div>
        </div>
			{/block}
			{block name="js"}
			<script>
		layui.use(['form', 'layer'],
            function() {
                $ = layui.jquery;
                var form = layui.form,
                layer = layui.layer;
                //监听提交
                form.on('submit(sok)',
                   function(data) {
				        var id=$("#textid").val();
				        var m=$("#RealMoney").val();
						layer.confirm('您确定该卡可用吗？', function(index){
								var loading =layer.load(3, {shade: [0.1,'#fff']});
								$.post("{:url('/Apiorder/setRest')}",{id:id,mianzi:m,'type':'ok'},function(res){
										layer.close(loading);
										if(res.code==1){
											layer.alert(res.msg,{icon:1},function(index){
												 layer.close();
												 window.parent.location.reload();
												 layer.closeAll();
											});
								        }else{
										layer.alert(res.msg,{icon:2});
										}
										
								})
							})
						return false;
                  
                });
				form.on('submit(sno)',
                   function(data) {
				        var id=$("#textid").val();
				        var e=$("#txtErrinfo").val();
						layer.confirm('您确定要订单赔付吗？', function(index){
								var loading =layer.load(3, {shade: [0.1,'#fff']});
								$.post("{:url('/Apiorder/setRest')}",{id:id,str:e,type:'err'},function(res){
										layer.close(loading);
										if(res.code==1){
											layer.alert(res.msg,{icon:1},function(index){
												 layer.close();
												 window.parent.location.reload();
												 layer.closeAll();
											});
										}else{
											layer.alert(res.msg,{icon:2});
										}
								})
							})
						return false;
                  
                });

            });</script>
				{/block}